// Assembles src/data/quotes.ts from the harvested src/data/corpus/*.json files.
// Grid: 6 topics × 5 eras × 6 heat levels; thin cells are backfilled from the
// nearest era of the same topic, then the same era of other topics.
// Run: node scripts/build-corpus.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const TOPICS = ['llms', 'rl', 'multimodal', 'scaling', 'agents', 'alignment'];
const ERAS = ['pre2012', 'e2012_2017', 'e2017_2020', 'e2020_2023', 'e2023_2026'];
const ERA_LABELS = ['pre-2012', '2012–17', '2017–20', '2020–23', '2023–26'];
const HEAT_LABELS = ['canon', 'mild', 'medium', 'hot', 'spicy', 'unhinged'];
const V = HEAT_LABELS.length;

const norm = (t) => (t || '').toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 48);

// pool[topic][era] = sorted candidate quotes
const pool = TOPICS.map(() => ERAS.map(() => []));
const seen = new Set();

for (let t = 0; t < TOPICS.length; t++) {
  const file = resolve(root, 'src/data/corpus', `${TOPICS[t]}.json`);
  const data = JSON.parse(readFileSync(file, 'utf8'));
  for (let e = 0; e < ERAS.length; e++) {
    for (const q of data.eras[ERAS[e]] ?? []) {
      const key = norm(q.text);
      if (!key || seen.has(key)) continue;
      if (!q.text || !q.author || q.text.length > 210) continue;
      seen.add(key);
      pool[t][e].push(q);
    }
    pool[t][e].sort((a, b) => (a.spice ?? 3) - (b.spice ?? 3));
  }
}

const attribution = (q) => `— ${q.author}${q.year ? `, ${q.year}` : ''}`;

// pick V quotes per cell with an even spread across the spice ordering
const used = new Set();
const grid = TOPICS.map(() => ERAS.map(() => []));
const stats = [];

function takeFrom(list, n) {
  const avail = list.filter((q) => !used.has(norm(q.text)));
  if (avail.length <= n) {
    avail.forEach((q) => used.add(norm(q.text)));
    return avail;
  }
  const picked = [];
  const idx = new Set();
  if (n === 1) idx.add(0);
  else for (let i = 0; i < n; i++) idx.add(Math.round((i * (avail.length - 1)) / (n - 1)));
  for (const i of [...idx].sort((a, b) => a - b)) picked.push(avail[i]);
  picked.forEach((q) => used.add(norm(q.text)));
  return picked;
}

for (let t = 0; t < TOPICS.length; t++) {
  for (let e = 0; e < ERAS.length; e++) {
    grid[t][e] = takeFrom(pool[t][e], V);
  }
}

// backfill thin cells: same topic, nearest era first; then same era, other topics
for (let t = 0; t < TOPICS.length; t++) {
  for (let e = 0; e < ERAS.length; e++) {
    let borrowed = 0;
    const need = () => V - grid[t][e].length;
    for (let d = 1; d < ERAS.length && need() > 0; d++) {
      for (const e2 of [e - d, e + d]) {
        if (e2 < 0 || e2 >= ERAS.length || need() <= 0) continue;
        const extra = takeFrom(pool[t][e2], need());
        borrowed += extra.length;
        grid[t][e].push(...extra);
      }
    }
    for (let dt = 1; dt < TOPICS.length && need() > 0; dt++) {
      const t2 = (t + dt) % TOPICS.length;
      const extra = takeFrom(pool[t2][e], need());
      borrowed += extra.length;
      grid[t][e].push(...extra);
    }
    if (need() > 0) throw new Error(`cell ${TOPICS[t]}/${ERAS[e]} still short by ${need()}`);
    grid[t][e].sort((a, b) => (a.spice ?? 3) - (b.spice ?? 3));
    stats.push(`${TOPICS[t]}/${ERAS[e]}: ${V - borrowed} own + ${borrowed} borrowed (pool ${pool[t][e].length})`);
  }
}

const entries = grid
  .map(
    (byEra, t) =>
      `  [\n${byEra
        .map(
          (cell) =>
            `    [\n${cell
              .map((q) => `      { text: ${JSON.stringify(q.text)}, attribution: ${JSON.stringify(attribution(q))} },`)
              .join('\n')}\n    ],`
        )
        .join('\n')}\n  ], // ${TOPICS[t]}`
  )
  .join('\n');

const out = `/* AUTO-GENERATED by scripts/build-corpus.mjs from src/data/corpus/*.json
   — do not edit by hand. Quotes were collected and fact-checked by a
   subagent workflow against primary/near-primary sources. */

export interface QuoteEntry {
  text: string;
  attribution: string;
}

export const TOPIC_LABELS = ${JSON.stringify(TOPICS)};
export const ERA_LABELS = ${JSON.stringify(ERA_LABELS)};
export const HEAT_LABELS = ${JSON.stringify(HEAT_LABELS)};

/** CORPUS[topic][era][heat] */
export const CORPUS: QuoteEntry[][][] = [
${entries}
];
`;

writeFileSync(resolve(root, 'src/data/quotes.ts'), out);
console.log(stats.join('\n'));
console.log(`total: ${grid.flat(2).length} quotes in grid, ${seen.size} unique harvested`);
console.log('default cell [0][2][0]:', JSON.stringify(grid[0][2][0]));
