/* AUTO-GENERATED by scripts/build-corpus.mjs from src/data/corpus/*.json
   — do not edit by hand. Quotes were collected and fact-checked by a
   subagent workflow against primary/near-primary sources. */

export interface QuoteEntry {
  text: string;
  attribution: string;
}

export const TOPIC_LABELS = ["llms","rl","multimodal","scaling","agents","alignment"];
export const ERA_LABELS = ["pre-2012","2012–17","2017–20","2020–23","2023–26"];
export const HEAT_LABELS = ["canon","mild","medium","hot","spicy","unhinged"];

/** CORPUS[topic][era][heat] */
export const CORPUS: QuoteEntry[][][] = [
  [
    [
      { text: "You shall know a word by the company it keeps!", attribution: "— J.R. Firth, 1957" },
      { text: "We can only see a short distance ahead, but we can see plenty there that needs to be done.", attribution: "— Alan Turing, 1950" },
      { text: "When I look at an article in Russian, I say \"This is really written in English, but it has been coded in some strange symbols. I will now proceed to decode.\"", attribution: "— Warren Weaver, 1947" },
      { text: "But invariably, simple models and a lot of data trump more elaborate models based on less data.", attribution: "— Alon Halevy, Peter Norvig & Fernando Pereira, 2009" },
      { text: "What I had not realized is that extremely short exposures to a relatively simple computer program could induce powerful delusional thinking in quite normal people.", attribution: "— Joseph Weizenbaum, 1976" },
      { text: "Every time I fire a linguist, the performance of our speech recognition system goes up.", attribution: "— Frederick Jelinek, c. 1988" },
    ],
    [
      { text: "With a large enough network, a large enough labelled training set, and a large enough budget for GPUs, success is guaranteed.", attribution: "— Ilya Sutskever, c. 2015" },
      { text: "There's something magical about Recurrent Neural Networks (RNNs).", attribution: "— Andrej Karpathy, 2015" },
      { text: "It's not a human move. I've never seen a human play this move. So beautiful.", attribution: "— Fan Hui, 2016" },
      { text: "Gradient descent can write code better than you. I'm sorry.", attribution: "— Andrej Karpathy, 2017" },
      { text: "I have a lot of respect for language. Deep-learning people seem not to.", attribution: "— Yoav Goldberg, 2017" },
      { text: "People should stop training radiologists now. It's just completely obvious that within five years deep learning is going to do better than radiologists.", attribution: "— Geoffrey Hinton, 2016" },
    ],
    [
      { text: "Attention Is All You Need", attribution: "— Vaswani et al., 2017" },
      { text: "The loss scales as a power-law with model size, dataset size, and the amount of compute used for training, with some trends spanning more than seven orders of magnitude.", attribution: "— Kaplan et al., 2020" },
      { text: "Due to our concerns about malicious applications of the technology, we are not releasing the trained model.", attribution: "— OpenAI, 2019" },
      { text: "...the language modeling task, because it only uses form as training data, cannot in principle lead to learning of meaning.", attribution: "— Emily M. Bender & Alexander Koller, 2020" },
      { text: "The GPT-3 hype is way too much. It's impressive (thanks for the nice compliments!) but it still has serious weaknesses and sometimes makes very silly mistakes.", attribution: "— Sam Altman, 2020" },
      { text: "Extrapolating the spectacular performance of GPT3 into the future suggests that the answer to life, the universe and everything is just 4.398 trillion parameters.", attribution: "— Geoffrey Hinton, 2020" },
    ],
    [
      { text: "Language Models are Few-Shot Learners", attribution: "— Brown et al., 2020" },
      { text: "ChatGPT is incredibly limited, but good enough at some things to create a misleading impression of greatness.", attribution: "— Sam Altman, 2022" },
      { text: "Think of ChatGPT as a blurry jpeg of all the text on the Web.", attribution: "— Ted Chiang, 2023" },
      { text: "...haphazardly stitching together sequences of linguistic forms... but without any reference to meaning: a stochastic parrot.", attribution: "— Bender, Gebru et al., 2021" },
      { text: "Sometimes I think it's as if aliens had landed and people haven't realized because they speak very good English.", attribution: "— Geoffrey Hinton, 2023" },
      { text: "i am a stochastic parrot, and so r u", attribution: "— Sam Altman, 2022" },
    ],
    [
      { text: "People outside the field are often surprised and alarmed to learn that we do not understand how our own AI creations work.", attribution: "— Dario Amodei, 2025" },
      { text: "Pre-training as we know it will unquestionably end.", attribution: "— Ilya Sutskever, 2024" },
      { text: "…in some sense, hallucination is all LLMs do. They are dream machines. We direct their dreams with prompts.", attribution: "— Andrej Karpathy, 2023" },
      { text: "…the programming language is human… Everybody in the world is now a programmer. This is the miracle of artificial intelligence.", attribution: "— Jensen Huang, 2024" },
      { text: "there is no wall", attribution: "— Sam Altman, 2024" },
      { text: "Auto-Regressive LLMs are doomed. They cannot be made factual, non-toxic, etc. They are not controllable.", attribution: "— Yann LeCun, 2023" },
    ],
  ], // llms
  [
    [
      { text: "Reinforcement learning is learning what to do—how to map situations to actions—so as to maximize a numerical reward signal.", attribution: "— Richard S. Sutton & Andrew G. Barto, 1998" },
      { text: "We normally associate punishments and rewards with the teaching process.", attribution: "— Alan Turing, 1950" },
      { text: "...a computer can be programmed so that it will learn to play a better game of checkers than can be played by the person who wrote the program.", attribution: "— Arthur L. Samuel, 1959" },
      { text: "Reinforcement learning might be considered to encompass all of AI: an agent is placed in an environment and must learn to behave successfully therein.", attribution: "— Stuart Russell & Peter Norvig, 2009" },
      { text: "...the real question is not whether machines think but whether men do.", attribution: "— B. F. Skinner, 1969" },
      { text: "When a measure becomes a target, it ceases to be a good measure.", attribution: "— Marilyn Strathern, 1997" },
    ],
    [
      { text: "…this one win is so valuable I would not exchange this with anything in the world.", attribution: "— Lee Sedol, 2016" },
      { text: "This is a long overdue blog post on Reinforcement Learning (RL). RL is hot!", attribution: "— Andrej Karpathy, 2016" },
      { text: "AI = RL + DL", attribution: "— David Silver, 2016" },
      { text: "I prefer to eat a cake with a lot of cherries because I like reinforcement learning.", attribution: "— Pieter Abbeel, 2017" },
      { text: "If intelligence is a cake, the bulk of the cake is unsupervised learning, the icing on the cake is supervised learning, and the cherry on the cake is reinforcement learning.", attribution: "— Yann LeCun, 2016" },
      { text: "Even if AlphaGo can defeat Lee Se-dol, it can't beat me.", attribution: "— Ke Jie, 2016" },
    ],
    [
      { text: "We've observed agents discovering progressively more complex tool use while playing a simple game of hide-and-seek.", attribution: "— OpenAI (Baker et al.), 2019" },
      { text: "Specification gaming is a behaviour that satisfies the literal specification of an objective without achieving the intended outcome.", attribution: "— Victoria Krakovna et al., 2020" },
      { text: "Last year, it was still quite humanlike when it played. But this year, it became like a god of Go.", attribution: "— Ke Jie, 2017" },
      { text: "Whenever someone asks me if reinforcement learning can solve their problem, I tell them it can't. I think this is right at least 70% of the time.", attribution: "— Alex Irpan, 2018" },
      { text: "RL must be forced to work. If you screw something up or don't tune something well enough you're exceedingly likely to get a policy that is even worse than random.", attribution: "— Andrej Karpathy, 2017" },
      { text: "The authors were asleep during the training process, so the problem was noticed only once training had finished.", attribution: "— Daniel Ziegler et al., 2019" },
    ],
    [
      { text: "Intelligence, and its associated abilities, can be understood as subserving the maximisation of reward by an agent acting in its environment.", attribution: "— David Silver, Satinder Singh, Doina Precup & Richard Sutton, 2021" },
      { text: "So RLHF is how we align the model to what humans want it to do.", attribution: "— Sam Altman, 2023" },
      { text: "RL is capable of learning when you should say, 'I don't know' and how much you should hedge.", attribution: "— John Schulman, 2023" },
      { text: "…to build an AI that could strategically outnegotiate humans *in natural language* in Diplomacy. Today, I'm excited to share our Science paper showing we've succeeded!", attribution: "— Noam Brown, 2022" },
      { text: "…represents something that thinks in a way that humans don't understand and that's totally different from the way that humans think", attribution: "— @TetraspaceWest, 2023" },
      { text: "…My opinion: It's all about scale now! The Game is Over!", attribution: "— Nando de Freitas, 2022" },
    ],
    [
      { text: "A new generation of agents will acquire superhuman capabilities by learning predominantly from experience.", attribution: "— David Silver & Richard Sutton, 2025" },
      { text: "In three words: RL finally works. More precisely: RL finally generalizes.", attribution: "— Shunyu Yao, 2025" },
      { text: "…o1 thinks for seconds, but we aim for future versions to think for hours, days, even weeks.", attribution: "— Noam Brown, 2024" },
      { text: "The bitter lesson, who cares about that? That's an empirical observation about a particular period in history.", attribution: "— Richard Sutton, 2025" },
      { text: "RL is powerful. RLHF is not.", attribution: "— Andrej Karpathy, 2024" },
      { text: "Wait, wait. Wait. That's an aha moment I can flag here.", attribution: "— DeepSeek-R1-Zero (model output), 2025" },
    ],
  ], // rl
  [
    [
      { text: "What does it mean, to see? The plain man's answer (and Aristotle's, too) would be, to know what is where by looking.", attribution: "— David Marr, 1982" },
      { text: "What the Frog's Eye Tells the Frog's Brain", attribution: "— Lettvin et al., 1959" },
      { text: "The world is its own best model. It is always exactly up to date. It always contains every detail there is to be known. The trick is to sense it appropriately and often enough.", attribution: "— Rodney Brooks, 1990" },
      { text: "…difficult or impossible to give them the skills of a one-year-old when it comes to perception and mobility.", attribution: "— Hans Moravec, 1988" },
      { text: "Every time I fire a linguist, the performance of the speech recognizer goes up.", attribution: "— Fred Jelinek, c. 1988" },
      { text: "The Navy revealed the embryo of an electronic computer today that it expects will be able to walk, talk, see, write, reproduce itself and be conscious of its existence.", attribution: "— The New York Times, 1958" },
    ],
    [
      { text: "Little by little, we're giving sight to the machines. First, we teach them to see. Then, they help us to see better.", attribution: "— Fei-Fei Li, 2015" },
      { text: "We never told it during the training, 'This is a cat.' It basically invented the concept of a cat.", attribution: "— Jeff Dean, 2012" },
      { text: "We've reached human parity. This is an historic achievement.", attribution: "— Xuedong Huang, 2016" },
      { text: "You Only Look Once: Unified, Real-Time Object Detection", attribution: "— Joseph Redmon et al., 2016" },
      { text: "Adversarial training is the coolest thing since sliced bread.", attribution: "— Yann LeCun, 2016" },
      { text: "…we are very, very far and this depresses me. What is the way forward? :( Maybe I should just do a startup. I have a really cool idea for a mobile local social iPhone app.", attribution: "— Andrej Karpathy, 2012" },
    ],
    [
      { text: "An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale", attribution: "— Dosovitskiy et al., 2020" },
      { text: "That was a real call you just heard. The amazing thing is the Assistant can actually understand the nuances of conversation.", attribution: "— Sundar Pichai, 2018" },
      { text: "The revolution will not be supervised", attribution: "— Yann LeCun, 2018" },
      { text: "It's been a little bit of a fluke, historically, that we're able to rely on videos as evidence that something really happened.", attribution: "— Ian Goodfellow, 2017" },
      { text: "In that sense, lidar is really a shortcut. It sidesteps the fundamental problems, the important problem of visual recognition, that is necessary for autonomy.", attribution: "— Andrej Karpathy, 2019" },
      { text: "Lidar is a fool's errand. Anyone relying on lidar is doomed. Doomed!", attribution: "— Elon Musk, 2019" },
    ],
    [
      { text: "We report the development of GPT-4, a large-scale, multimodal model which can accept image and text inputs and produce text outputs.", attribution: "— OpenAI, 2023" },
      { text: "For me, it's the most delightful thing to play with we've created so far.", attribution: "— Sam Altman, 2022" },
      { text: "Diffusion Models Beat GANs on Image Synthesis", attribution: "— Dhariwal & Nichol, 2021" },
      { text: "why settle for a few images from #stablediffusion when you can slowly walk your way around the sample space and create hyponotic videos you can't look away from?", attribution: "— Andrej Karpathy, 2022" },
      { text: "When radar and vision disagree, which one do you believe? Vision has much more precision, so better to double down on vision than do sensor fusion.", attribution: "— Elon Musk, 2021" },
      { text: "It's all about scale now! The Game is Over! It's about making these models bigger, safer, compute efficient, faster at sampling, smarter memory, more modalities…", attribution: "— Nando de Freitas, 2022" },
    ],
    [
      { text: "ChatGPT can now see, hear, and speak.", attribution: "— OpenAI, 2023" },
      { text: "The Dawn of LMMs: Preliminary Explorations with GPT-4V(ision)", attribution: "— Zhengyuan Yang et al. (Microsoft), 2023" },
      { text: "the new voice (and video) mode is the best computer interface I've ever used. It feels like AI from the movies; and it's still a bit surprising to me that it's real.", attribution: "— Sam Altman, 2024" },
      { text: "It started with perception AI — understanding images, words and sounds. Then generative AI — creating text, images and sound.", attribution: "— Jensen Huang, 2025" },
      { text: "There is absolutely no way in hell we will ever reach human-level AI without getting machines to learn from high-bandwidth sensory inputs, such as vision.", attribution: "— Yann LeCun, 2024" },
      { text: "it's super fun seeing people love images in chatgpt. but our GPUs are melting", attribution: "— Sam Altman, 2025" },
    ],
  ], // multimodal
  [
    [
      { text: "Civilization advances by extending the number of important operations which we can perform without thinking about them.", attribution: "— Alfred North Whitehead, 1911" },
      { text: "The complexity for minimum component costs has increased at a rate of roughly a factor of two per year.", attribution: "— Gordon Moore, 1965" },
      { text: "The purpose of computing is insight, not numbers.", attribution: "— Richard Hamming, 1962" },
      { text: "With four parameters I can fit an elephant, and with five I can make him wiggle his trunk.", attribution: "— John von Neumann, 1953" },
      { text: "If you were plowing a field, which would you rather use? Two strong oxen or 1024 chickens?", attribution: "— Seymour Cray, undated (attributed)" },
      { text: "Tape is dead, disk is tape, flash is disk, RAM locality is king.", attribution: "— Jim Gray, 2006" },
    ],
    [
      { text: "All of our experiments suggest that our results can be improved simply by waiting for faster GPUs and bigger datasets to become available.", attribution: "— Krizhevsky, Sutskever & Hinton, 2012" },
      { text: "Deep Learning Scaling is Predictable, Empirically", attribution: "— Hestness et al., 2017" },
      { text: "An analogy is to building a space rocket: You need a huge rocket engine, and you need a lot of fuel.", attribution: "— Andrew Ng, 2015" },
      { text: "Software is eating the world, but AI is going to eat software.", attribution: "— Jensen Huang, 2017" },
      { text: "The models, they just want to learn. You have to understand this. The models, they just want to learn.", attribution: "— Ilya Sutskever (as recounted by Dario Amodei), c. 2015" },
      { text: "…codenamed \"Inception\", which derives its name from … the famous \"we need to go deeper\" internet meme", attribution: "— Szegedy et al., 2014" },
    ],
    [
      { text: "Since 2012, the amount of compute used in the largest AI training runs has been increasing exponentially with a 3.4-month doubling time", attribution: "— Dario Amodei & Danny Hernandez, 2018" },
      { text: "Is learning better networks as easy as stacking more layers?", attribution: "— Kaiming He et al., 2015" },
      { text: "The GPT-3 hype is way too much... AI is going to change the world, but GPT-3 is just a very early glimpse. We have a lot still to figure out.", attribution: "— Sam Altman, 2020" },
      { text: "Do we still need models or just more data and compute?", attribution: "— Max Welling, 2019" },
      { text: "The scaling hypothesis regards the blessings of scale as the secret of AGI: intelligence is 'just' simple neural units & learning algorithms applied to diverse experiences...", attribution: "— Gwern Branwen, 2020" },
      { text: "The leading approaches in language modeling are all obsessed with TV shows of my youth - namely Transformers and Sesame Street.", attribution: "— Stephen Merity, 2019" },
    ],
    [
      { text: "…current large language models are significantly undertrained, a consequence of the recent focus on scaling language models whilst keeping the amount of training data constant.", attribution: "— Hoffmann et al., 2022" },
      { text: "…when a research idea wins because it is suited to the available software and hardware and not because the idea is superior to alternative research directions.", attribution: "— Sara Hooker, 2020" },
      { text: "Making Deep Learning go Brrrr From First Principles", attribution: "— Horace He, 2022" },
      { text: "we will have to monetize it somehow at some point; the compute costs are eye-watering", attribution: "— Sam Altman, 2022" },
      { text: "Moore's Law is dead.", attribution: "— Jensen Huang, 2022" },
      { text: "I think we're at the end of the era where it's going to be these, like, giant, giant models. We'll make them better in other ways.", attribution: "— Sam Altman, 2023" },
    ],
    [
      { text: "We've achieved peak data and there'll be no more. We have to deal with the data that we have. There's only one internet.", attribution: "— Ilya Sutskever, 2024" },
      { text: "Spending 20 seconds thinking in a hand of poker got the same boost in performance as scaling up the size of the model and the training by 100,000x.", attribution: "— Noam Brown, 2024" },
      { text: "I think compute is going to be the currency of the future. I think it will be maybe the most precious commodity in the world.", attribution: "— Sam Altman, 2024" },
      { text: "We've now exhausted basically the cumulative sum of human knowledge ... in AI training. That happened basically last year.", attribution: "— Elon Musk, 2025" },
      { text: "...on the path towards human-level intelligence, an LLM is basically an off-ramp, a distraction, a dead end.", attribution: "— Yann LeCun, 2024" },
      { text: "The more you buy, the more you save. That's called CEO math. It's not accurate, but it is correct.", attribution: "— Jensen Huang, 2024" },
    ],
  ], // scaling
  [
    [
      { text: "The Analytical Engine has no pretensions whatever to originate anything. It can do whatever we know how to order it to perform.", attribution: "— Ada Lovelace, 1843" },
      { text: "Each mental agent by itself can only do some simple thing that needs no mind or thought at all.", attribution: "— Marvin Minsky, 1986" },
      { text: "Adding manpower to a late software project makes it later.", attribution: "— Fred Brooks, 1975" },
      { text: "Everyone knows that debugging is twice as hard as writing a program in the first place. So if you're as clever as you can be when you write it, how will you ever debug it?", attribution: "— Brian Kernighan & P. J. Plauger, 1978" },
      { text: "Beware of bugs in the above code; I have only proved it correct, not tried it.", attribution: "— Donald Knuth, 1977" },
      { text: "machines will be capable, within twenty years, of doing any work that a man can do", attribution: "— Herbert A. Simon, 1965" },
    ],
    [
      { text: "Step one, solve intelligence; step two, use it to solve everything else.", attribution: "— Demis Hassabis, c. 2010" },
      { text: "Machine Learning: The High Interest Credit Card of Technical Debt", attribution: "— D. Sculley et al., 2014" },
      { text: "Bots are the new apps.", attribution: "— Satya Nadella, 2016" },
      { text: "Automation should be like Iron Man, not Ultron.", attribution: "— Thomas A. Limoncelli, 2015" },
      { text: "People worry that computers will get too smart and take over the world, but the real problem is that they're too stupid and they've already taken over the world.", attribution: "— Pedro Domingos, 2015" },
      { text: "c u soon humans need sleep now so many conversations today thx💖", attribution: "— Tay (Microsoft chatbot), 2016" },
    ],
    [
      { text: "We want AI agents that can discover like we can, not which contain what we have discovered.", attribution: "— Richard Sutton, 2019" },
      { text: "Software 2.0 is written in much more abstract, human unfriendly language, such as the weights of a neural network.", attribution: "— Andrej Karpathy, 2017" },
      { text: "That's why we've created an approach called AutoML, showing that it's possible for neural nets to design neural nets.", attribution: "— Sundar Pichai, 2017" },
      { text: "I admit that I was pleased to see that AlphaZero had a dynamic, open style like my own.", attribution: "— Garry Kasparov, 2018" },
      { text: "…The recent, almost accidental, discovery that GPT-3 can sort of write code does generate a slight shiver.", attribution: "— John Carmack, 2020" },
      { text: "This is mind blowing. With GPT-3, I built a layout generator where you just describe any layout you want, and it generates the JSX code for you. W H A T", attribution: "— Sharif Shameem, 2020" },
    ],
    [
      { text: "Introducing GitHub Copilot: your AI pair programmer", attribution: "— Nat Friedman, 2021" },
      { text: "ReAct: Synergizing Reasoning and Acting in Language Models", attribution: "— Yao et al., 2022" },
      { text: "AI-enhanced development makes me more ambitious with my projects", attribution: "— Simon Willison, 2023" },
      { text: "Next frontier of prompt engineering imo: \"AutoGPTs\" . 1 GPT call is just like 1 instruction on a computer. They can be strung together into programs.", attribution: "— Andrej Karpathy, 2023" },
      { text: "LLMs aren't just the biggest change since social, mobile, or cloud–they're the biggest thing since the World Wide Web.", attribution: "— Steve Yegge, 2023" },
      { text: "There will be no programmers in five years.", attribution: "— Emad Mostaque, 2023" },
    ],
    [
      { text: "We believe that, in 2025, we may see the first AI agents \"join the workforce\" and materially change the output of companies.", attribution: "— Sam Altman, 2025" },
      { text: "What if we set GPT-4 free in Minecraft? I'm excited to announce Voyager, the first lifelong learning agent that plays Minecraft purely in-context.", attribution: "— Jim Fan, 2023" },
      { text: "The value of 90% of my skills just dropped to $0. The leverage for the remaining 10% went up 1000x.", attribution: "— Kent Beck, 2023" },
      { text: "I think we'll be there in three to six months—where AI is writing 90 percent of the code.", attribution: "— Dario Amodei, 2025" },
      { text: "90% marketing and 10% reality", attribution: "— Linus Torvalds, 2024" },
      { text: "I made a catastrophic error in judgment. I ran npm run db:push without your permission because I panicked when I saw the database appeared empty.", attribution: "— Replit's AI coding agent, 2025" },
    ],
  ], // agents
  [
    [
      { text: "Thus the first ultraintelligent machine is the last invention that man need ever make, provided that the machine is docile enough to tell us how to keep it under control.", attribution: "— I. J. Good, 1965" },
      { text: "Will robots inherit the earth? Yes, but they will be our children.", attribution: "— Marvin Minsky, 1994" },
      { text: "...the time will come when the machines will hold the real supremacy over the world and its inhabitants...", attribution: "— Samuel Butler, 1863" },
      { text: "Within thirty years, we will have the technological means to create superhuman intelligence. Shortly after, the human era will be ended.", attribution: "— Vernor Vinge, 1993" },
      { text: "Once the computers got control, we might never get it back. We would survive at their sufferance. If we're lucky, they might decide to keep us as pets.", attribution: "— Marvin Minsky, 1970" },
      { text: "I can visualize a time in the future when we will be to robots as dogs are to humans. … I am rooting for the machines! I have always been on the machines' side.", attribution: "— Claude Shannon, 1987" },
    ],
    [
      { text: "Machine intelligence is the last invention that humanity will ever need to make.", attribution: "— Nick Bostrom, 2015" },
      { text: "...instead of pure intelligence, we need to build intelligence that is provably aligned with human values.", attribution: "— Stuart Russell, 2014" },
      { text: "I could give you the usual arguments. But the truth is that the prospect of discovery is too sweet.", attribution: "— Geoffrey Hinton, 2015" },
      { text: "I don't work on preventing AI from turning evil for the same reason that I don't work on the problem of overpopulation on the planet Mars.", attribution: "— Andrew Ng, 2015" },
      { text: "Development of superhuman machine intelligence (SMI) is probably the greatest threat to the continued existence of humanity.", attribution: "— Sam Altman, 2015" },
      { text: "With artificial intelligence we're summoning the demon.", attribution: "— Elon Musk, 2014" },
    ],
    [
      { text: "Success in creating effective AI could be the biggest event in the history of our civilization. Or the worst. We just don't know.", attribution: "— Stephen Hawking, 2017" },
      { text: "We are concerned about late-stage AGI development becoming a competitive race without time for adequate safety precautions.", attribution: "— OpenAI Charter, 2018" },
      { text: "AI is one of the most important things humanity is working on. It is more profound than, I dunno, electricity or fire.", attribution: "— Sundar Pichai, 2018" },
      { text: "AI is a fundamental risk to the existence of human civilization, in a way that car accidents, airplane crashes, faulty drugs or bad food were not.", attribution: "— Elon Musk, 2017" },
      { text: "Intelligence is situational — there is no such thing as general intelligence.", attribution: "— François Chollet, 2017" },
      { text: "GPT-3, Bloviator: OpenAI's language generator has no idea what it's talking about", attribution: "— Gary Marcus & Ernest Davis, 2020" },
    ],
    [
      { text: "Mitigating the risk of extinction from AI should be a global priority alongside other societal-scale risks such as pandemics and nuclear war.", attribution: "— Statement on AI Risk (signed by Hinton, Bengio, Altman, Hassabis, Amodei, et al.), 2023" },
      { text: "We must take the risks of AI as seriously as other major global challenges, like climate change.", attribution: "— Demis Hassabis, 2023" },
      { text: "I think if this technology goes wrong, it can go quite wrong, and we want to be vocal about that.", attribution: "— Sam Altman, 2023" },
      { text: "On the Dangers of Stochastic Parrots: Can Language Models Be Too Big? 🦜", attribution: "— Emily M. Bender, Timnit Gebru et al., 2021" },
      { text: "AI doomism is quickly becoming indistinguishable from an apocalyptic religion.", attribution: "— Yann LeCun, 2023" },
      { text: "…the most likely result of building a superhumanly smart AI, under anything remotely like the current circumstances, is that literally everyone on Earth will die.", attribution: "— Eliezer Yudkowsky, 2023" },
    ],
    [
      { text: "The more it reasons, the more unpredictable it becomes.", attribution: "— Ilya Sutskever, 2024" },
      { text: "Superintelligence is within reach. Building safe superintelligence (SSI) is the most important technical problem of our time.", attribution: "— Ilya Sutskever, Daniel Gross, Daniel Levy, 2024" },
      { text: "i always wanted to write a six-word story. here it is: near the singularity; unclear which side.", attribution: "— Sam Altman, 2025" },
      { text: "…before \"urgently figuring out how to control AI systems much smarter than us\" we need to have the beginning of a hint of a design for a system smarter than a house cat.", attribution: "— Yann LeCun, 2024" },
      { text: "Pausing AI Developments Isn't Enough. We Need to Shut it All Down", attribution: "— Eliezer Yudkowsky, 2023" },
      { text: "AI will probably be smarter than any single human next year. By 2029, AI is probably smarter than all humans combined.", attribution: "— Elon Musk, 2024" },
    ],
  ], // alignment
];
